spring.application.name=ecommerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=MYsql1234@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate related setting
# =============================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Spring Security

spring.security.user.name=admin@123
spring.security.user.password=admin@123
#
#
## JWT settings
#spring.app.jwtSecret=feyfidjfodffufiutruidjfisidosioeufifuiifrutieiyueryeryueyrerueyrueyfjdhfjdhfjdfhfhuhrutejidjkledjfkhri
#spring.app.jwtExpirationMs=172800000


#2 days

Razorpay.key=rzp_test_S060WMnc2eFoWe
Razorpay.secret=4XRX50lBHOXxPQ9Nwlrb6HxU

logging.level.org.springframework.security=DEBUG

#Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mo111faiz@gmail.com
spring.mail.password=zokz rdln ftdh zbae
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# images

#workshop.images=images/workshops/
#request.images=images/requests/